### ISSUE TITLE
Implementing (not deriving) foreign traits for generated types?

### ISSUE THREAD

**Issue by andrew-otiv** [tokio-rs/prost#1108]
I would like to implement, i.e. TryInto for some of our types generated by prost. Is there a way to include code, probably in the  "rust_prost_library" bazel target, that includes a .rs file as a dependency, in which I can place trait implementations?

It seems like I could embed source code in my Bazel file as a string, and pass it into the type_attribute:
https://docs.rs/prost-build/0.5.0/prost_build/struct.Config.html#method.type_attribute

but that's probably not going to work with rust_analyzer, or cache well since it's outside the build graph.

I also see extern_path:
https://docs.rs/prost-build/0.5.0/prost_build/struct.Config.html#method.extern_path
but that takes a proto file too, so it doesn't seem like the right thing.

**Comment by caspermeijn** [comment]
First of all, I don't have experience with bazel, so I can't help you with that.

If you follow the example from [`prost-build` docs](https://docs.rs/prost-build/latest/prost_build/), you have a lib.rs which includes the generated files. You could add your impls there. For example:

```rust
use prost::Name;
use alloc::string::String;

include!(concat!(env!("OUT_DIR"), "/type_names.rs"));

impl Into<String> for Foo {
    fn into(self) -> String {
        Foo::full_name()
    }
}
```

**Comment by andrew-otiv** [comment]
Thanks for the response! In hindsight this is indeed more of a build issue.
