### ISSUE TITLE
[Question/Feature-Request] Support for creating Message from string name

### ISSUE THREAD

**Issue by jonahgeorge** [tokio-rs/prost#113]
Are there any plans to implement the equivalent of the [`DescriptorDatabase`](https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.descriptor_database#SimpleDescriptorDatabase.FindFileByName.details) from the C++ implementation or [`proto.MessageType`](https://godoc.org/github.com/golang/protobuf/proto#MessageType) from Go?  

I have a particular use case that needs the ability to create a Protobuf message from the string name of the message and afaict this is not possible in Prost. The current workaround seems to be re-processing the Protobuf files and constructing a map of string to message which is very undesirable.

**Comment by danburkert** [comment]
Could you elaborate on what such an API might look like?  I've never encountered `DescriptorDatabase`, so I'm not exactly sure what it's used for.  Does this require reflection features?  Currently `prost` doesn't have any reflection capability.

**Comment by jonahgeorge** [comment]
I'm not super familiar with Prost yet so forgive me if this doesn't make sense, but I would imagine an API similar to:

```rust
fn from_name(name: String) -> impl Message 
```

So that you could do something along the lines of:

```rust
let message_type = "User".to_string(); // Potentially coming from a query param
let body = ""; // Coming from POST body

let input = prost::from_name(message_type).decode(body);
```

For example, here's a [StackOverflow post](https://stackoverflow.com/a/29975019/3712711) about the behavior in C++.

---

Given we can't reflect on the Rust types, one thought is to generate a lib.rs file in the directory that Prost writes the messages to with a HashMap of message name to message type. However, I'm not particularly happy with this solution.

I mainly just wanted to raise awareness of this feature in the other implementations and begin discussing a way to implement it.

**Comment by danburkert** [comment]
> `fn from_name(name: String) -> impl Message`

Not a comment on the overall idea, but this isn't how the impl trait feature works; the API would need to be `fn from_name(name: String) -> Box<dyn Message>`.

> So that you could do something along the lines of: ...

Is this actually useful?  If you can't do anything with the decoded generic `Message` instance for lack of a generic API I don't see much use.  Actually creating a generic API for `prost` is definitely an open design question.  It's critical that `Message` be object safe, which makes designing such an API difficult.
