### ISSUE TITLE
compile_protos nested import seems failed

### ISSUE THREAD

**Issue by Yongle-Fu** [tokio-rs/prost#1132]
a.proto
```
message Foo {
uint32 bar = 1
}
```

b.proto
```
import "a.proto";
```

c.proto
```
import "a.proto";
import "b.proto";
```

\"Foo\" seems to be defined in seems to be defined in \"b.proto\", which is not imported by \"c.proto\"

**Comment by Yongle-Fu** [comment]
just build c.proto only is fine

**Comment by caspermeijn** [comment]
Can you explain how compile_protos is called? Maybe you could share a complete rust crate that shows your problem?

21 aug. 2024 08:11:49 Yongle-Fu ***@***.***>:

**Comment by Yongle-Fu** [comment]
```rust
let stark_proto_files = ["proto3/a.proto", "proto3/b.proto", "proto3/c.proto"];
    let stark_include_dirs = ["proto3/stark"];
    compile_protos(
        &stark_proto_files,
        &stark_include_dirs,
    );
```
build failed.

```rust
let stark_proto_files = ["proto3/c.proto"];
    let stark_include_dirs = ["proto3/stark"];
    compile_protos(
        &stark_proto_files,
        &stark_include_dirs,
    );
```
work fine.

**Comment by caspermeijn** [comment]
@Yongle-Fu I am unable to reproduce your problem. Could you share a complete project with this issue? Maybe a new GitHub repo or, even better, a test case in the `prost` repo?

**Comment by Yongle-Fu** [comment]
Thanks for reply. 

[reproduce demo](https://github.com/Yongle-Fu/proto_test)

**Comment by caspermeijn** [comment]
You forgot to mention that there is this error message:

```
  Failed to compile protos: Custom { kind: Other, error: "protoc failed: b.proto:4:16: \"FooB.bar\" is already defined in file \"test/b.proto\".\nb.proto:3:9: \"FooB\" is already defined in file \"test/b.proto\".\ntest/c.proto:4:1: Import \"b.proto\" was not found or had errors.\ntest/c.proto:8:9: \"FooB\" seems to be defined in \"test/b.proto\", which is not imported by \"test/c.proto\".  To use it here, please add the necessary import.\n" }
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The formatting is not so nice, but it tells me the following:
- The protobuf compiler (`protoc`) produced this error
- It mentions both: "test/b.proto" and "b.proto"
- It mentions that FooB double defined

My conclusion is that `b.proto` is imported via multiple paths, and that is the actual problem. You need to refer to the file with a consistent path. For example:
- `import "test/b.proto";`
- Remove one of the two `stark_include_dirs` definitions.

With either of these changed, your demo builds correctly. Please let me know if this solves your problem.

**Comment by Yongle-Fu** [comment]
remove duplicate import can work fine.
