### ISSUE TITLE
Clippy warning of unwrap usage in generated code

### ISSUE THREAD

**Issue by bittermandel** [tokio-rs/prost#1170]
I've been trying every method possible to ignore the unwrap usage in the generated tonic servers, but I can't seem to achieve it.

I include the generated files like this:
```rust
pub mod valv {
    pub mod proto {
        pub mod v1 {
            #![allow(clippy::unwrap_used)]
            include!("gen/valv.v1.rs");
        }
    }
}
```

valv.v1.rs has a `include!("valv.v1.tonic.rs");` call in the bottom of it, which is the file that actually has the unwrap call. Allowing unwrap_used works for `valv.v1.rs`, but the tonic file will still warn.

Is there a way to make Prost add clippy annotations in files, or in some other way add annotations when including code?

**Comment by caspermeijn** [comment]
`clippy::unwrap_used` is an allow by default lint. `prost` doesn't guarantee that this lint is followed. I am open to a PR that improves the unwrap usage such that this lint can be enabled. 

Improvements to the `tonic` generated code have to be submitted to the tonic project.

I think you already found the easiest way to handle this situation: Add an allow to the generated module. The best way is to improve `prost`.
