### ISSUE TITLE
Implement my traits on generated Enum

### ISSUE THREAD

**Issue by dimitri-correia** [tokio-rs/prost#1185]
## Problem Description

I'm trying to iterate over the values of an enum generated by Prost, which is something I typically achieve using the [Strum crate](https://docs.rs/strum_macros/latest/strum_macros/derive.EnumIter.html) with the `EnumIter` trait. However, since the enum is generated by Prost (prost-build), I can't directly use Strum here.

## What I’ve Tried

I looked for a way to iterate over the Prost-generated enum, but it seems that this isn’t currently supported, or at least I couldn’t find a method. My workaround idea was to add the enum manually in my Rust code rather than defining it in my `.proto` file, using "Tag Inference for Existing Types" with `use prost::{Enumeration, Message};`. However, this leads to errors since the `.proto` file requires the enum to be defined within it.

## Proposal

Could we consider adding a feature flag in Prost to allow additional traits on enums, such as an iterator? This would make it easier to iterate over enums generated from `.proto` files without additional workarounds.
I can start to look into creating a PR for this, but I want to be sure it's something that is wanted and possible to achieve.

What are your thoughts on this?

**Comment by caspermeijn** [comment]
I think you are looking for the `prost_build::Config` type. You can configure the generated output to derive strum. You probably want to use https://docs.rs/prost-build/latest/prost_build/struct.Config.html#method.type_attribute

The existence of `Config` is not documented well. Where did you look to find documentation about solving this issue? Are you willing to open a PR to add some example?

9 nov. 2024 14:00:24 Dimitri CORREIA ***@***.***>:
