### ISSUE TITLE
Missing documentation for ::prost::Oneof

### ISSUE THREAD

**Issue by sezna** [tokio-rs/prost#237]
Thanks for prost. I use it for a lot of projects and it has served us well.

Recently, my company started using `#![deny(missing_docs)]`, and I am getting the following error:
```
warning: missing documentation for a method
   |
10 |     #[derive(Clone, PartialEq, ::prost::Oneof)]
   |                                ^^^^^^^^^^^^^^

```

How can I add a docstring for `::prost::Oneof`? It is not a matter of it being documented in the prost crate itself, as denying missing docs ignores docs outside of my project, so there must be a way for me to document it within my project, right? Or if not, perhaps there should be?

Thanks.

**Comment by dunmatt** [comment]
Ping!  I'm running into the same issue, except it's missing documentation for the nested enum wrapper modules.  I'd really love to not have to make exceptions for all my message types.

**Comment by cbrune** [comment]
Agree with @sezna  -- thanks for prost!  It's quite great.

I made a little repo that reproduces this problem here: https://github.com/cbrune/prost-doc

I'm happy to help, but need to be pointed in the right direction.
