### ISSUE TITLE
Improve the usage of decode_length_delimiter / Message::decode_length_delimited

### ISSUE THREAD

**Issue by mawenqi** [tokio-rs/prost#285]
Say the buf received is like:
```
// the total length of following two struct with fixed width(4)
0x00, 0x00, 0x00, 0x32, // = 50
// varint encoding of struct A length 
0x1e, // = 30
0x08, 0x02, 0x10, 0x00, 0x18, 0xfd, 0xff, 0xff, 0xff, 0x0f,
0x22, 0x10, 0x87, 0xeb, 0x86, 0xd4, 0x9c, 0x95, 0x4c, 0x15,
0x8a, 0xb0, 0xd7, 0xbc, 0x2e, 0xca, 0xca, 0x37, 0x28, 0x01,
// varint encoding of struct B length 
0x12, // = 18
0x12, 0x0a, 0x0a, 0x08, 0x65, 0x6c, 0x65, 0x69, 0x62, 0x6f,
0x76, 0x69, 0x1a, 0x04, 0x70, 0x69, 0x6e, 0x67
```

How can we decode it? It seems we have to do this:
```
let len = buf.get_i32();  // len = 50
    
let a_len = decode_length_delimiter(buf.clone())?; // a_len = 30
let a_len_len = length_delimiter_len(a_len);  // a_len_len = 1
buf.advance(a_len_len);
let a_buf = buf.split_to(a_len); 
let a = A::decode(a_buf)?;
    
let b_len = decode(buf.clone())?;  // b_len = 18
let b_len_len = length_delimiter_len(b_len);  // b_len_len = 1
buf.advance(b_len_len);
let b_buf = buf.split_to(b_len); 
let b = B::decode(b_buf)?;
```
As you can see, it is tedious. Is there a better way?  Many thanks.

BTW, if decode_length_delimiter and Message::decode_length_delimited 
could just consume accurate size of the buf but not the whole, then I can do this:
```
let len = buf.get_i32();  // len = 50
let a = A::decode_length_delimited(&mut buf)?;
let b = B::decode_length_delimited(&mut buf)?;
```
Thanks.

**Comment by danburkert** [comment]
In general, it's up to the application to decide how to do message delimiting (see [upstream docs](https://developers.google.com/protocol-buffers/docs/techniques#streaming)).  Part of the reason that looks awkward is that you are cloning `buf` before passing it into `decode_length_delimiter`, then calling `advance` manually; `decode_length_delimiter` should advance the internal buffer the correct amount automatically.

**Comment by mawenqi** [comment]
Unfortunately, `decode_length_delimiter` also consumes the whole buf, that is why I have to clone the `buf` and call the `advance` manually.

**Comment by danburkert** [comment]
pass a mutable reference to the buffer to `decode_length_delimited`.

**Comment by caspermeijn** [comment]
I think the last response is the solution to this problem
