### ISSUE TITLE
Make prost_build::compile_protos add a warning to the top of the file: `// This file is automatically generated as part of the build process. Do not edit it!`

### ISSUE THREAD

**Issue by evandrocoan** [tokio-rs/prost#308]
https://docs.rs/prost-build/0.6.1/prost_build/fn.compile_protos.html

Currently, the generated file has no warning on the top, as an indication it is a generated file. This warning is quite helpful for new users learning the project.

**Comment by caspermeijn** [comment]
In the latest version the generated file starts with: `// This file is @generated by prost-build.`

I think that completes this issue. Please re-open if you think otherwise.

**Comment by evandrocoan** [comment]
Thanks. That should do it!
