### ISSUE TITLE
Documentation needs a "Hello World" example 

### ISSUE THREAD

**Issue by hjfreyer** [tokio-rs/prost#346]
I'm struggling to find a simple, copy-pastable example of simply serializing and serializing a proto.

**Comment by danburkert** [comment]
The [snazzy](https://github.com/danburkert/snazzy) project is a 'hello world' style example.  It hasn't been updated since 0.5, but the API didn't change drastically.

**Comment by zdannar** [comment]
I also am trying to work through finding an example and stumbling.  I have a call to redis that have protobuf data and I am trying to decode it into a struct.  Not much luck thus far.

**Comment by zdannar** [comment]
I finally figured it out and have something working.  This helped a bunch.  https://hockeybuggy.com/blog/post/2020/01/experimenting-with-protobufs-generated-types-in-rust

**Comment by hjfreyer** [comment]
@danburkert friendly ping on my PR above.
