### ISSUE TITLE
Include LICENSE file in prost-derive crate

### ISSUE THREAD

**Issue by nullr0ute** [tokio-rs/prost#353]
The LICENSE file isn't shipped in the prost-derive crate, it is in the prost crate.

**Comment by nullr0ute** [comment]
Nor is it shipped in prost-build or rust-prost-types crates

**Comment by danburkert** [comment]
Would accept a PR!  If the repo has symlinks would `cargo publish` handle that correctly, or does it have to be actual file copies?

**Comment by caspermeijn** [comment]
This has been fixed in the latest release
