### ISSUE TITLE
Attributes on WKT

### ISSUE THREAD

**Issue by kalzoo** [tokio-rs/prost#375]
First of all, I'd like to say I got to this point really quickly and easily, thanks to how intuitive `prost` is to use, thanks for your work!

Related to #255 and #145. didn't see this directly addressed in past issues.

Looking to add attribute`#[derive(Deserialize)]` on a number of generated structs. It worked well until the dependency tree swept in a `google.protobuf.Any`, and the same problem occurred with a `google.protobuf.Struct`. I think this should be a `prost` issue rather than `serde`, because it revolves around attributes on the generated message structs.

My build.rs is set up like:

```rust
    let mut config = prost_build::Config::new();
    config.type_attribute(".my_package.common", "#[derive(serde_derive::Deserialize)]");
    // ...

    config.compile_protos(
        &[
            "../protobuf/common/common.proto",
            // ...
        ],
        &["../protobuf/"],
    )
    .unwrap();
```

Original problem: 

```
error[E0277]: the trait bound `prost_types::Struct: serde::Deserialize<'_>` is not satisfied
   --> /Users/.../target/debug/build/.../out/....rs:488:9
    |
488 |         #[prost(message, optional, tag="3")]
    |         ^ the trait `serde::Deserialize<'_>` is not implemented for `prost_types::Struct`
    |
    = note: required because of the requirements on the impl of `serde::Deserialize<'_>` for `std::option::Option<prost_types::Struct>`
    = note: required by `serde::de::SeqAccess::next_element`

```

Then I tried `config.compile_well_known_types()` in the hopes that I could then attach type attributes, but even without changes to the attributes configuration, got a number of errors like this (this seems like it could be a distinct issue, but it may be a misconfiguration on my part somewhere):

```
error[E0433]: failed to resolve: there are too many leading `super` keywords
   --> /Users/.../target/debug/build/.../out/....rs:489:57
    |
489 |         pub params: ::std::option::Option<super::super::super::google::protobuf::Struct>,
    |                                                         ^^^^^ there are too many leading `super` keywords

error[E0283]: type annotations needed
   --> /Users/.../target/debug/build/..../out/....rs:160:28
    |
160 | #[derive(Clone, PartialEq, ::prost::Message)]
    |                            ^^^^^^^^^^^^^^^^ cannot infer type
    |
    = note: cannot satisfy `_: std::default::Default`
    = note: required by `std::default::Default::default`
    = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

I also tried something silly like this to no effect:

```
config.type_attribute("Struct", "#[derive(serde_derive::Deserialize)]");
```

The options as I see them:
1. `impl Deserialize` on `prost_types::Any`
2. Re-implement `Any` within my own .proto file, so that the type will be generated locally and I can attach an attribute to it.

Tangible question: is there a better way to generate the WKT in a way that I can annotate them?

Thanks!

**Comment by danburkert** [comment]
Hmm for now I think you're only way forward is to compile the WKTs yourself with the derive annotations attached.  I'm not sure what's going on with the compilation issue - if you can create an example repro or test in the `tests/` directory of `prost` and share it that would be helpful to getting to the bottom of it.

I'm very keen to add support for the protobuf JSON encoding to `prost` by having an option to output the right serde annotations, however I haven't found time to actually work on this.  Once that's done, they could be enabled for `prost-types` through a cargo feature.  I can't give a timeline on when this might land, though.

**Comment by migel** [comment]
you need to reconstruct the protobuf module path in rust. e.g.:

`build.rs`:
```rust
fn main() {
    let mut config = prost_build::Config::new();
    config.compile_well_known_types()
          .type_attribute(".", "#[derive(serde::Serialize, serde::Deserialize)]")
          .compile_protos(&["src/message.proto"], &["src/"])
          .unwrap();
}
```
`src/main.rs`:
```rust
pub mod google {
    pub mod protobuf {
        include!(concat!(env!("OUT_DIR"), "/google.protobuf.rs"));
    }
}

pub mod a {
    pub mod b {
        pub mod c {
            include!(concat!(env!("OUT_DIR"), "/a.b.c.rs"));
        }
    }
}

fn main() {
    let data = r#"
    {
        "ts": { "seconds": 123, "nanos": 456 },
        "object": { "type_url": "xyz", "value": [1, 2] }
    }
    "#;
    let h: a::b::c::Hello = serde_json::from_str(data).unwrap();
    println!("{:?}", h);
}
```
`src/message.proto`:
```protobuf
syntax = "proto3";
package a.b.c;

import "google/protobuf/any.proto";
import "google/protobuf/timestamp.proto";

message Hello {
    google.protobuf.Timestamp ts = 1;
    google.protobuf.Any object = 2;
}
```

see also https://stackoverflow.com/questions/58040435/how-to-generate-codes-using-prost-in-rust

**Comment by kalzoo** [comment]
Yes, sorry for the delay, that's correct! Thanks @migel
