### ISSUE TITLE
Add optional support for generating std::time::SystemTime for .google.protobuf.Timestamp

### ISSUE THREAD

**Issue by danburkert** [tokio-rs/prost#416]
See #414 for previous discussion & motivation.

**Comment by danburkert** [comment]
This is related to #404, at least in spirit.

**Comment by nathanperkins** [comment]
Having a hard time using prost_types::Timestamp without the ability to convert into SystemTime.

**Comment by LucioFranco** [comment]
Actually this has been solved https://docs.rs/prost-types/latest/prost_types/struct.Timestamp.html#impl-TryFrom%3CTimestamp%3E-for-SystemTime
