### ISSUE TITLE
skipping build stage

### ISSUE THREAD

**Issue by barkanido** [tokio-rs/prost#424]
This is a bit off-topic, but I hope that a good discussion here would benefit others.

### Problem description:
I am using prost `build.rs` hooks to generate my files with `protoc`, and I want to build my application as a Docker image. The `.proto` files reside in another repository outside of the Docker build context. Therefore, `compile_protos` refers to directories that are outside my Docker build context (project root directory: `../proto-dir/...`). This causes the build to obviously fail because Docker can't see the paths outside the project root. Docker's `COPY` command also rightly forbids copying stuff from outside.
_Clarification_: I do commit the generated code into the source control as I believe it is a good practice anyway.
### Possible solutions:

1. Include the proto repo as a Git submodule. This way, the `.proto` files are always included.
2. Somehow, skip the generation phase as default and make it optional (maybe passing an environment variable or a command-line flag) so users can generate code only if they decide it is necessary (the other repo has advanced in an important way).
3. Let docker solve it:
   - By changing the build context to the parent dir (this will require to jump a few hoops in the CI, I guess) 
   - Mounting docker volumes (not sure it is a valid path).
   - Let Docker pull the repo inside the working directory every time (will probably hot a few authorization related walls).
4. Another creative idea.

I am interested to know which path is considered best practice and is the simplest to achieve.

**Comment by caspermeijn** [comment]
I don't think there is an issue that prost can fix. Please re-open if you think otherwise.
