### ISSUE TITLE
question: working with prost_types::Struct

### ISSUE THREAD

**Issue by jwinarske** [tokio-rs/prost#435]
How does one work with converting Value as used in prost_types::Struct?

Say value of "my_key" is a String.

            let map = device.traits.unwrap().fields;
            for (key, value) in map {
                println!("\t{}", key);
            }
            let status = &map["my_key"];

I want to print the String value of status.

Neither of these work:

    let s: String = status.try_into().unwrap();

    println!("{}", String::from(status));

A simple example of Value conversion would be greatly appreciated.

**Comment by jwinarske** [comment]
This pattern works, albeit not pretty.  Is there a better way?

```
match status.kind.as_ref().unwrap() {
    Kind::NullValue(_) => {
        println!("\t\t\tNullValue");
    }
    Kind::NumberValue(num) => {
        println!("\t\t\t{}", PrettyPrintFloat(*num));
    }
    Kind::StringValue(str) => {
        println!("\t\t\t\"{}\"", str);
    }
    Kind::BoolValue(b) => {
        println!("\t\t\tBoolValue: {}", b);
    }
    Kind::StructValue(_) => {
        println!("\t\t\tStructValue");
    }
    Kind::ListValue(list) => {
        for item in &list.values {
            println!("\t\t\tList item");
        }
    }
}

```

**Comment by caspermeijn** [comment]
I feel like this is more a rust question then a prost question. All types in `prost_types` do implement `trait Debug`, so `println!("{:?}", status);` should work.
