### ISSUE TITLE
Is trait.Message.html#method.encode the preferred way to encode a message?

### ISSUE THREAD

**Issue by Jasperav** [tokio-rs/prost#461]
Is https://docs.rs/prost/0.7.0/prost/trait.Message.html#method.encode the general way to encode messages? It takes a buffer. A quick look in:

- https://github.com/danburkert/prost/blob/32ad5a2e1036a9c9425f0a84f032ba9f343b133e/protobuf/benches/dataset.rs#L49
- https://www.swiftdiaries.com/rust/prost/

both use the encoded_len of the message for the capacity of the buffer. https://hockeybuggy.com/blog/post/2020/01/experimenting-with-protobufs-generated-types-in-rust uses just a value of 200 'to be sure'. That looks a little bit odd to me.

My question is: what should be the value of the buffer? Isn't it always the encoded_len of the same message? If so, why is the buffer parameter needed?

**Comment by rubdos** [comment]
The reason that you can specify it, is because you may be encoding this into part of an existing buffer. That said, through #378 you would have the most common case of prost doing the allocation for you, for a single message.

**Comment by LucioFranco** [comment]
Seems like #378 should fix this.
