### ISSUE TITLE
Feature Proposal:  a prost-include proc macro to generate modules and includes

### ISSUE THREAD

**Issue by dunmatt** [tokio-rs/prost#470]
Over in https://crates.io/crates/prost it says "All Rust types generated from the file will be in the foo::bar module.", which is a bit misleading, since the generated code doesn't identify any module that it is in.  Instead, it's up to the user to `include!` the files into appropriately named modules.  It makes perfect sense why the user would have to do this: Rust doesn't allow multiple module definitions the way it allows multiple impl blocks for a type, and messages will likely share ancestor modules.

Instead, I'm wondering if you'd be open to a PR that introduces a proc-macro called `prost-include`, where you give it a list of generated `rs` files and it takes care of the rest, a la:

    prost-include!(m.a, m.b, m.c);

and it generates:

    pub mod m {
        pub mod a {
            include!(concat!(env!("OUT_DIR"), "/m.a.rs"));
        }
        pub mod b {
        ...
    }

**Comment by LegNeato** [comment]
Potentially relevant: https://github.com/danburkert/prost/pull/433

**Comment by LucioFranco** [comment]
Closing because of #433
