### ISSUE TITLE
Manual include generated files

### ISSUE THREAD

**Issue by incker** [tokio-rs/prost#479]
Hello,

Include generated files using macro is not clear for IDE (intellijy idea) So I have no IDE hints.

It could be easily fixed by including generated files in a  common way like `use proto::*`

But generated file names contains dot like `some.items.rs` that breaks all rust syntax

Thanks for any help

**Comment by LegNeato** [comment]
Potentially relevant: https://github.com/danburkert/prost/pull/433

**Comment by LucioFranco** [comment]
I believe using #433 should help.
