### ISSUE TITLE
Clarify maintenance expectations

### ISSUE THREAD

**Issue by LegNeato** [tokio-rs/prost#481]
First of all, thank you very much for this library!

There are currently some smaller but useful PRs that have no review or comments for weeks. Additionally, the last commit to master was a month ago. Can we help the maintainers scale in any way?

It would be great to know what expectations contributors should have for PR merging and new releases so we can plan appropriately.

**Comment by carllerche** [comment]
Prost moved into the tokio-rs to leverage the maintainers there.
