### ISSUE TITLE
proto3 defines that all fields are optional; In prost, they are not. 

### ISSUE THREAD

**Issue by singerxt** [tokio-rs/prost#520]
Hello!

First of all, thank you so much for working on Prost!

I'm a little bit confused because the proto3 specification says that every field is _optional_. So I'm expecting protofile will be compiled to this:
```proto
message  Foo {
    string name = 1;
}
```
-> 
```rust
pub struct Foo {
    pub name: Option<alloc::string::String>,
}
```
In this way, I will be able to create a Foo object with None in the name

```rust
let foo = Foo {
  name: None,
}
```

However, prost generated code disallows me to create optional fields because the output of compiled code will be 

```rust
pub struct Foo {
    pub name: alloc::string::String,
}
```

Please correct me if I'm wrong.

**Comment by danburkert** [comment]
> I'm a little bit confused because the proto3 specification says that every field is optional.

I don't believe that's the case, can you link to the relevant part of the proto3 spec?  proto3 recently added support for explicitly optional scalar fields, and I believe prost supports that.

**Comment by singerxt** [comment]
You're right :-)
