### ISSUE TITLE
can prost serialize/deserialize text format and json?

### ISSUE THREAD

**Issue by binbowang1987** [tokio-rs/prost#541]

**Comment by andrewhickman** [comment]
I've implemented JSON serialization and deserialization in [prost_reflect](https://docs.rs/prost-reflect/latest/prost_reflect/). It passes all the protobuf conformance tests so I'd consider it "complete", although it would be great to get some real-world testing.

Unlike pbjson however, it doesn't support serializing existing `Message` structs directly, only by first converting to [`DynamicMessage`](https://docs.rs/prost-reflect/latest/prost_reflect/struct.DynamicMessage.html).

**Comment by WestXu** [comment]
So I've found this, if anyone doesn't know already:
```Rust
// build.rs

use std::io::Result;
fn main() -> Result<()> {
    let mut prost_build = prost_build::Config::new();
    prost_build
        .type_attribute(".", "#[derive(serde::Serialize,serde::Deserialize)]")
        .compile_protos(&["src/jzs.proto", "src/md.proto"], &["src/"])?;

    Ok(())
}
```
Then the generated code will derive serde, with json ser/de capability.

**Comment by liufuyang** [comment]
Indeed, those `type_attribute` and `field_attribute` can be helpful, but for some reason, it is not working for all the protobuf types, such as `Any`. 

I found this thing - https://github.com/fdeantoni/prost-wkt and it seems could help with those issues. I wish `prost` could have some sort of good support directly to allow the generated Rust code to work with json :)

**Comment by caspermeijn** [comment]
The answer to the question is: no, currently `prost` can't convert to/from JSON. But it is something that has been requested a lot. See https://github.com/tokio-rs/prost/issues/75
