### ISSUE TITLE
`super` generated too many times when calling other imported .proto messages

### ISSUE THREAD

**Issue by mattrighetti** [tokio-rs/prost#545]
I have found a strange error in protobuf generation while I was using Prost in conjunction with Tonic.

Running on
```
Darwin Kernel Version 21.1.0: Thu Sep 23 21:17:10 PDT 2021; root:xnu-8019.40.86.181.1~2/RELEASE_X86_64 x86_64 i386 MacBookPro16,1 Darwin

rustc 1.55.0 (c8dfcfe04 2021-09-06)

cargo 1.55.0 (32da73ab1 2021-08-23)
```

My project has this folder structure
```sh
.
├── build.rs
├── Cargo.lock
├── Cargo.toml
├── proto
│  └── org
│     ├── api
│     │  └── general.proto
│     ├── service1
│     │  └── v1
│     │     └── service1.proto
│     └── service2
│        └── v1
│           └── service2.proto
└── src
   └── server.rs
```

**general.proto**
```protobuf
syntax = "proto3";

package org.api;

message General {
    string general = 5;
    string description = 6;
};
```

**service1.proto**
```protobuf
syntax = "proto3";

import "org/api/general.proto";

package org.service1.v1;

service Service1 {
    rpc Send(Service1Request) returns (Service1Response);
}

message Service1Request {
    org.api.General general = 5;
    string description = 6;
}

message Service1Response {
    string response = 5;
}
```

**service2.proto**
```protobuf
syntax = "proto3";

import "org/api/general.proto";

package org.service2.v1;

service Service2 {
    rpc Send(Service2Request) returns (Service2Response);
}

message Service2Request {
    org.api.General general = 5;
    int32 value = 6;
    string description = 7;
}

message Service2Response {
    string response = 5;
}
```

**build.rs**
Here I am building just `service1` but the same happens with `service2`.
```rust
use std::env;
use std::path::PathBuf;

fn main() {
    tonic_build::configure()
    .build_client(false)
    .compile(
        &["proto/org/service1/v1/service1.proto"],
        &["proto"]
    )
    .unwrap();
}
```

It seems like it doesn't like when I use `org.api.General` in `service1` and `service2` because the build returns this error

```
error[E0433]: failed to resolve: there are too many leading `super` keywords
 --> /Users/user/Desktop/test-build/target/debug/build/test-build-25050f1b68bb5218/out/org.service1.v1.rs:4:48
  |
4 |     pub general: ::core::option::Option<super::super::api::General>,
  |                                                ^^^^^ there are too many leading `super` keywords
```

The fix that I've found for the moment is to just include `General` both in `service1` and in `service2` with code duplication, how can this be solved?

Project here
[test-build.zip](https://github.com/tokio-rs/prost/files/7285098/test-build.zip)

**Comment by DerekStrickland** [comment]
I solved this with the [include_file](https://github.com/tokio-rs/prost/blob/db9cd5ce138950051dc9e8af6f3585a7661bdaa5/prost-build/src/lib.rs#L739) function.

That said, 2 caveats. 

1. I don't think it's in a release yet so you would need to patch locally with 

```toml
[patch.crates-io]
prost = { git = "https://github.com/tokio-rs/prost" }
```

2. There's a bug in it if you are using it with `out_dir`.  I've submitted [this PR](https://github.com/tokio-rs/prost/pull/544), but I don't believe it's been merged.  You could probably patch off that fork though.  

I realize this a workaround until a release, but hopefully it gets you unstuck.

**Comment by LucioFranco** [comment]
So either you need to use that new feature which will ship with prost 0.9 or move all the proto files to be in the same folder I believe this will also fix your issue.

**Comment by mattrighetti** [comment]
Turns out I was importing stuff incorrectly, I saw the correct version generated by `prost` 0.9 and it works now. Closing this issue
