### ISSUE TITLE
Fix clippy warnings introduced with 2021 edition

### ISSUE THREAD

**Issue by LucioFranco** [tokio-rs/prost#553]

**Comment by chetaldrich** [comment]
So I looked into this just because I was curious, and noticed that there were a decent number of warnings already showing up without changing the edition. Would you be willing to take a look at a PR that addresses existing warnings?

**Comment by chetaldrich** [comment]
I gave it a whirl. If you have a chance to take a look at some point I'd appreciate it!

**Comment by chetaldrich** [comment]
That being said, we can fix clippy errors with 2021 in stable, we just can't set the library to 2021.

**Comment by LucioFranco** [comment]
Yeah I am good to fix clippy errors, we can follow up on the edition update.

**Comment by chetaldrich** [comment]
I went ahead and followed up with that edition update so we can close this out.
