### ISSUE TITLE
Possible bug: Prost skips serialising integers if they are equal to 0

### ISSUE THREAD

**Issue by Vurich** [tokio-rs/prost#554]
While Protobuf will deserialise unset scalar fields as 0 (or empty string/byte vec), this may not be correct as it breaks expected behaviour when changing a field from non-repeated to repeated. If the sender of the message considers the field non-repeated it will send nothing, but if the receiver considers it repeated it will deserialise that as an empty collection - instead of the expected result, which is a collection with a single element with a value of 0. Is this intended, and do official Google implementations do the same?

**Comment by danburkert** [comment]
My understanding is that this is allowed by the spec, and most official implementations do do it.  It makes more sense when you look at it from the lense of 0 being the 'default' value; in either case you skip serializing the default value, and on de-serialization you receive the default value.

**Comment by jaskij** [comment]
You do not specify whether you're using `proto2` or `proto3`. Judging by lack of references to `optional` or `required`, `proto3` seems like a safe assumption.

----

This is an expected behavior.

> Also note that if a scalar message field is set to its default, the value will not be serialized on the wire.

https://developers.google.com/protocol-buffers/docs/proto3#default

> For any non-repeated fields in proto3, or optional fields in proto2, the encoded message may or may not have a key-value pair with that field number.

https://developers.google.com/protocol-buffers/docs/encoding#optional

Furthermore, the [instructions for updating a message type](https://developers.google.com/protocol-buffers/docs/proto3#updating) don't mention any sort of compatibility between scalar number fields and `repeated` fields.

**Comment by jaskij** [comment]
Looking further, I was not aware that [`optional` was added back to `proto3`](https://github.com/protocolbuffers/protobuf/blob/master/docs/field_presence.md) - once #457 is fixed this might work well if you mark your scalar number value as optional.

**Comment by Vurich** [comment]
Good point, I should have specified that I’m using proto3. Ok, thank you for the very helpful information and links, it’s frankly a little frustrating that the rules are often so arbitrary but that’s not the problem of prost. To confirm: do you always need to provide a value for `optional` scalar fields, even if that value is default?

**Comment by jaskij** [comment]
> To confirm: do you always need to provide a value for optional scalar fields, even if that value is default?

If my reading is correct, for `optional` fields in proto3, if you do not provide a value, it is not serialized. If you do provide a value, it is always serialized, regardless of it being the default.
