### ISSUE TITLE
Tuple structs with enumerations don't work

### ISSUE THREAD

**Issue by vorner** [tokio-rs/prost#56]
It seems tuple structs are broken when they contain an enumeration. I hit it when implementing tests for https://github.com/danburkert/prost/pull/54, but I can reproduce on master:

```rust
/// A special case with a tuple struct
#[test]
fn tuple_struct() {
    #[derive(Clone, PartialEq, Message, Debug)]
    struct NewType(
        #[prost(int32, tag="1")]
        pub i32,
        #[prost(enumeration="BasicEnumeration", tag="5")]
        pub i32,
    );
}
```

The error is:

```
   Compiling conformance v0.0.0 (file:///home/vorner/prog/prost/conformance)
error: expected identifier, found `1`
   --> tests/src/lib.rs:152:32
    |
152 |     #[derive(Clone, PartialEq, Message, Debug)]
```

If I comment the second field out,it compiles. I had no success yet pinpointing where exactly it happens, because cargo expand gives me the same error instead of the (broken) source code. 

As the prost-derive code contains code to handle tuple structs, I guess they are supposed to work.

**Comment by danburkert** [comment]
Yeah, since the code generator doesn't output tuple structs they are not well tested (if at all).  Let's leave this open as documentation of the bug.  I don't use hand-written structs except for tests, so it won't be at the top of my to-do list to fix.
