### ISSUE TITLE
Security: avoid storing binary artifacts for `protoc` binary

### ISSUE THREAD

**Issue by tmfink** [tokio-rs/prost#562]
Thanks for your great work with this crate.

# Situation

The `prost-build` crate seems to use cached, pre-compiled binaries for the `protoc` by default:
https://github.com/tokio-rs/prost/tree/master/prost-build/third-party/protobuf

Users can opt out of this behavior by setting the `PROTOC` environment variable:
https://github.com/tokio-rs/prost/blob/c3b7037a7f2c56cef327b41ca32a8c4e9ce5a41c/prost-build/build.rs#L102-L108

# Problem

It's surprising that this crate would use a pre-compiled binary artifact by default.
Those concerned with supply-chain security don't want to unwittingly rely on binary artifacts

In fact, in the software security space, the [Software Bill of Materials (SBOM)](https://www.ntia.gov/SBOM) movement has gained traction, where vendors show where all code comes from. In the United States, there was an [executive order](https://www.whitehouse.gov/briefing-room/presidential-actions/2021/05/12/executive-order-on-improving-the-nations-cybersecurity/) mandating that vendors providing software to the government provide an SBOM. It would not look good if a vendor unwittingly relied on a binary artifact.

The Open Source Security Foundation (OpenSSF) [classifies storing binary artifacts in the repo as a high-risk security concern](https://github.com/ossf/scorecard/blob/af594d39210f97029cd207e32b703939cf42b177/docs/checks.md#binary-artifacts). I don't want to re-iterate every point, but the high-level point is that while not impossible to review, binaries are much more difficult to validate compared to source code. This makes it easier for an attacker to insert malicious code.

For example, in a recent [breach of the JavaScript NPM package `ua-parser-js`](https://us-cert.cisa.gov/ncas/current-activity/2021/10/22/malware-discovered-popular-npm-package-ua-parser-js), attackers inserted malware into the package. This is especially bad since (as of writing) that package has about 6 million weekly downloads.

As of writing, crates.io shows that  [`prost` has 368 public reverse dependencies](https://crates.io/crates/prost/reverse_dependencies). That does not include unpublished/proprietary code or transitive reverse dependencies. There are probably many users of `prost` who don't know they are users of `prost` (due the `prost` existing somewhere in the dependency graph) :wink:.

# Solutions

Note that either of these is a backwards-incompatible change and would require a version bump.

## Minimum Fix

At a minimum, using the binary artifacts should not be default. Using the pre-compiled binaries should be opt-in instead of opt-out.

For example, users could set the `PROTOC_USE_PRECOMPILED_BINARY` to use the pre-built binary. Otherwise, the `PROTOC` variable would be queried (possible fallback to `PATH`). If no `protoc` can be found, the `build.rs` would panic.

## Recommended Fix

Ideally, no pre-compiled binaries should be used at all. Instead, vendor the [protobuf sources](https://github.com/protocolbuffers/protobuf) in this repo. I suggest avoiding git submodules and copying the sources directly into this repo[^avoid-git-submodules].

This also has the benefit of making it *easier* to support more platforms. For example, I hit an issue trying to compile code that depended on `prost` on a FreeBSD machine[^discover-issue-freebsd]. On such platforms, protobuf could just be compiled without needing to manually compile/install `protoc`.

[^avoid-git-submodules]: I maintain the [`capstone`](https://github.com/capstone-rust/capstone-rs) crate, which are Rust bindings to a C library. I [vendor the C library](https://github.com/capstone-rust/capstone-rs/tree/d8b874f3b9e610a32d7e1d5a884d875f0d2f9766/capstone-sys/capstone) and have a [script to update the vendored sources](https://github.com/capstone-rust/capstone-rs/blob/d8b874f3b9e610a32d7e1d5a884d875f0d2f9766/capstone-sys/scripts/update_capstone.sh).

[^discover-issue-freebsd]: That's how I actually discovered this issue

**Comment by benesch** [comment]
Hah, I just wrote up the exact same thing in #575, and put together a proposed fix in #576. Would love your feedback on that.

**Comment by tmfink** [comment]
> Hah, I just wrote up the exact same thing in #575, and put together a proposed fix in #576. Would love your feedback on that.

ACK--I put comments in #576 :smile:

**Comment by tmfink** [comment]
handled with #610
