### ISSUE TITLE
Accessor for oneof field

### ISSUE THREAD

**Issue by viirya** [tokio-rs/prost#565]
Does prost generate accessor for oneof field?

For a field, prost will generate the accessor `set_{fieldname}`, but seems for a oneof field, there is no such accessor. Do I use it correctly?

For example, the generated struct looks like:
```rust
pub struct Expr {
    #[prost(enumeration="expr::ExprType", tag="1")]
    pub expr_type: i32,
    #[prost(oneof="expr::ExprStruct", tags="2, 3")]
    pub expr_struct: ::core::option::Option<expr::ExprStruct>,
}
```

I can call `set_expr_type` but for `set_expr_struct`, I got:

```rust
error[E0599]: no method named `set_expr_struct` found for struct `expression::Expr` in the current scope
```

Although the fields are public and I still can assign it directly, I'm wondering if there is accessor.

**Comment by ljluestc** [comment]
Given your example:

```
pub struct Expr {
    #[prost(enumeration="expr::ExprType", tag="1")]
    pub expr_type: i32,
    #[prost(oneof="expr::ExprStruct", tags="2, 3")]
    pub expr_struct: ::core::option::Option<expr::ExprStruct>,
}
```
expr_struct would be an enum defined something like this:

```
pub mod expr {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum ExprStruct {
        #[prost(message, tag="2")]
        Variant1(StructType1),
        #[prost(message, tag="3")]
        Variant2(StructType2),
    }
}
```
To set expr_struct, you would do:

```
let mut expr = Expr::default();
expr.expr_struct = Some(expr::ExprStruct::Variant1(StructType1 { /* ... */ }));
// or 
expr.expr_struct = Some(expr::ExprStruct::Variant2(StructType2 { /* ... */ }));
```
The error you're encountering (error[E0599]: no method named set_expr_struct found) is because prost does not generate a set_expr_struct method for oneof fields. Instead, you directly assign to the expr_struct field, which is Option<expr::ExprStruct>.

**Comment by viirya** [comment]
Thanks @ljluestc. This was created long time ago and I forgot how we proceeded with it. Seems not an issue for us now.
