### ISSUE TITLE
Example of docs for `extern_path` doesn't compile

### ISSUE THREAD

**Issue by cortopy** [tokio-rs/prost#568]
I have followed the example for adding the 'uuid' crate as a dependency in here: https://docs.rs/prost-build/0.9.0/prost_build/struct.Config.html#usage

Everything works, as I can see the generated code is now:

```rust
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Order {
    #[prost(message, optional, tag = "1")]
    pub id: ::core::option::Option<::uuid::Uuid>,
..
}
```

however, it doesn't compile because `the trait prost::Message is not implemented for Uuid`

I find the docs confusing as I understood from this [issue](https://github.com/tokio-rs/prost/issues/537) that Uuid as an external crate is not supported anyway. This is me hoping that I'm missing something from the docs

**Comment by LucioFranco** [comment]
Checkout the answer in https://github.com/tokio-rs/prost/pull/637#issuecomment-1113561134
