### ISSUE TITLE
Incorrect deserialized result for oneof field

### ISSUE THREAD

**Issue by viirya** [tokio-rs/prost#569]
I define a `oneof` field which can have self-reference to the wrapping message. I use the protobuf to serialize some SQL expressions in JVM and deserialize in Rust. But sometimes the deserialized result is incorrect. I also deserialize in JVM too and verify that it is correct in JVM side. So it seems like a bug in `prost`.

The `.proto` files looks like:

```
message Expr {
  oneof expr_struct {
    Add add = 1;
    BoundReference bound = 2;
  }
}

message Add {
  Expr left = 1;
  Expr right = 2;
}

message BoundReference {
  int32 index = 1;
}
```

```
message Operator {
  oneof op_struct {
    Projection projection = 1;
  }
}

message Projection {
  repeated Expr project_list = 1;
  Operator child = 2;
}
```

The issue happens when the repeated field `project_list` has more than one `Expr`.

For example, an example message like:

```
projection {
  project_list {
    add {
      left {
        bound {
          index: 1
        }
      }
      right {
        bound {
          index: 2
        }
      }
    }
  }
  project_list {
    add {
      left {
        bound {
          index: 1
        }
      }
      right {
        bound {
          index: 2
        }
      }
    }
  }
}
```

At Rust side, `prost` sometimes decodes the second `bound` in the first `add`  to `bound { index: 0 }`. So the indexes becomes incorrect `[1, 0, 1, 2]` instead of `[1, 2, 1, 2]`.

**Comment by viirya** [comment]
The issue is not always happened, moreover. Running the same code on cmd line, sometimes the indexes are correct, sometimes are not.

**Comment by viirya** [comment]
More clue. Once I add another field to `BoundReference`, e.g.:

```
message BoundReference {
  int32 index = 1;
  DataType dt = 2;

  enum DataType {
    BOOL = 0;
    INT = 1;
  }
}
```

The message looks like:

```
projection {
  project_list {
    add {
      left {
        bound {
          index: 1
          dt: INT
        }
      }
      right {
        bound {
          index: 2
          dt: INT
        }
      }
    }
  }
  project_list {
    add {
      left {
        bound {
          index: 1
          dt: INT
        }
      }
      right {
        bound {
          index: 2
          dt: INT
        }
      }
    }
  }
}
```

Sometimes decoding fails with an error:
```
failed to decode Protobuf message: Expr.expr_struct: Add.right: Expr.expr_struct: Projection.project_list: Operator.op_struct: invalid wire type: Varint (expected LengthDelimited)
```

**Comment by viirya** [comment]
If I change the `index` from i32 to string, the error becomes:

```
failed to decode Protobuf message: Add.right: Expr.expr_struct: Projection.project_list: Operator.op_struct: invalid tag value: 0
```

**Comment by viirya** [comment]
This turns out to be that I used incorrect approach to retrieve bytearray through jni.

**Comment by danbosnichill** [comment]
Hi @viirya !  We just hit a similar bug.  We have oneof and self referencing protobuf messages.  The client runs Golang though.  Any ideas on how to solve this?  I'm curious if prost has an issue with this.

**Comment by viirya** [comment]
The issue is due to incorrect approach to get the serialized bytes through JNI. So it is not a bug for our case.
