### ISSUE TITLE
Supply chain security with embedded protoc binaries

### ISSUE THREAD

**Issue by benesch** [tokio-rs/prost#575]
We're thinking about using prost over at @MaterializeInc, but the supply chain security of the embedded `protoc` binaries has me very nervous.

Specifically: what sort of validation are you doing before you merge PRs to check that the binaries supplied by third parties are identical to the binaries published by google/protobuf? I did some spot checks and they look identical, but I didn't see anything in your CI pipeline that would assert this. 

We'd honestly probably want to opt out of the bundled protoc deps entirely. I know that's already possible if you specify `PROTOC`, but I'd feel better if there were a way to not even bring the binaries into our dependency tree. Otherwise it seems too easy for accidents to happen; e.g., if that env var somehow gets unset. 

How would y'all feel about adopting an approach similar to rust-protobuf, where the bundled binaries are kept in a separate crate (e.g., `prost-build-vendored`)? Using that crate could be enabled by default, but we could keep it off @MaterializeInc and lint for its absence using `cargo deny`, and I'd sleep a good bit easier at night.

I've also been toying with the idea of building something like `protobuf-src` for Rust (a la `openssl-src`) that builds libprotobuf from source and makes its protoc available to downstream libraries. That could be a nice alternative for `prost-build` to expose.

**Comment by LucioFranco** [comment]
Hey @benesch sorry for the delay on this I must have missed it somehow. Are you still interested in getting this working? I think the separate crate idea is good. 

cc @jonhoo I think you've been interested in some of this stuff too.

**Comment by jonhoo** [comment]
I think doing something along what's proposed here is a great idea!

**Comment by benesch** [comment]
No problem, @LucioFranco! Thanks for taking a look now. I actually whipped up a proposal in https://github.com/tokio-rs/prost/pull/576, but we need you or another maintainer to weigh in on how to expose the toggle of which `protoc` to use. The lack of mutually exclusive features in Cargo means there’s no great solution.

I’m also maintaining a fork of prost that _forces_ compiling protoc from source: https://github.com/materializeinc/prost. But I figure you probably don’t want to force a C++ dependency on all users of prost.

**Comment by benesch** [comment]
By the way, if it’s easiest to sync on Discord or something, happy to find the time!

**Comment by LucioFranco** [comment]
Yeah, let me try to catch up on everything so may be a bit slow then we can sync. I'd love for yall to not have to maintain a fork so I'd like to get this solved :)

**Comment by LucioFranco** [comment]
Ok I spent sometime today talking to @jonhoo about this and how we also want to not ship compiled binaries internally here.

I think the proposed solution in #576 is a step in the right direction but I think we will want to avoid having two mutually exclusive feature flags. I think the direction we should head should actually be to not ship any pre-compiled binaries and only allow users to either provide a `protoc` (similar to how we support it now) or to compile it thus requiring users to have a C++ toolchain on hand.

So I think we should follow this sort of flow for obtaining a `protoc`:

- If `PROTOC_NO_VENDOR`
	- excute from `PATH` or fail
- else if `prost-build/vendored` feature is enabled or `protoc` is not found in `PATH`
	- compile `protoc` from source and execute from there
- else
	- excute from `PATH` or fail


I believe this solves most of our issues, while this may increase build times for users that don't have a `protoc` installed on their systems, I do think this will overall improve the security posture of `prost` for all our customers.

**Comment by benesch** [comment]
> I think the proposed solution in https://github.com/tokio-rs/prost/pull/576 is a step in the right direction but I think we will want to avoid having two mutually exclusive feature flags. I think the direction we should head should actually be to not ship any pre-compiled binaries and only allow users to either provide a protoc (similar to how we support it now) or to compile it thus requiring users to have a C++ toolchain on hand.

This sounds even better than my PR!

**Comment by LucioFranco** [comment]
@benesch I am working on a PR for this, ill post it in here and tag you on it once its ready. Thanks again for getting this rolling!

**Comment by benesch** [comment]
Sounds wonderful! You are taking an even stronger stance on this than I had hoped, so I am delighted!
