### ISSUE TITLE
How to manually generate a Rust code from the given *.proto file(s) without usage of extra build step (with `prost-build`)?

### ISSUE THREAD

**Issue by dnrusakov** [tokio-rs/prost#578]
How to manually generate a Rust code from the given *.proto file(s) without usage of extra build step (with `prost-build`)?

Currently, `prost-build` generates the Rust code into `OUT_DIR` directory. 
That works, but breaks code highlighting and competition in CLion (with Rust plugin, of course).

**Comment by lz1998** [comment]
> How to manually generate a Rust code from the given *.proto file(s) without usage of extra build step (with `prost-build`)?
> 
> Currently, `prost-build` generates the Rust code into `OUT_DIR` directory. That works, but breaks code highlighting and competition in CLion (with Rust plugin, of course).

1. Press `shift` 3 times
2. Open `Experimental Features`
3. Check `org.rust.cargo.evaluate.build.scripts`
4. Execute `cargo check`
5. Restart CLion

**Comment by dnrusakov** [comment]
@lz1998 Thank you!

**Comment by maoueh** [comment]
Another idea is to actually convert the `build.rs` into a main script instead. So you run it outside of the build process when convenient.

Here our that we hook into the project as a dedicated crate with a binary.

```
fn main() {
    tonic_build::configure()
        .out_dir("./src/codec")
        .format(true)
        .compile(
            &["sf/near/codec/v1/codec.proto"],
            &["../proto", "../proto-near"],
        )
        .unwrap_or_else(|e| panic!("Failed to compile near dm proto(s) {:?}", e));
}
```

We made it a sub-crate inside our project and when required, we run it. See https://github.com/streamingfast/near-dm-indexer/tree/develop/deepmind-pb

**Comment by LucioFranco** [comment]
You can change the directory it builds into. Another option is to actually do the proto generation in a test so that and puts the code into some checked in dir. This way it doesn't run under the `build.rs` step. Going to close this issue since I think its resolved. Feel free to reopen if you have anymore questions.
