### ISSUE TITLE
why i can't decode caffe.prototxt file?

### ISSUE THREAD

**Issue by corleonechensiyu** [tokio-rs/prost#579]
`let mut file = std::fs::File::open("F:\\study\\tensor\\src\\lenet.prototxt").unwrap();`
`let mut v = vec![];`
`file.read_to_end(&mut v).unwrap();`
`let b = bytes::Bytes::from(v);`
`let r = NetParameter::decode(b);`
`println!("{:?}",r);`
it return error like this.
**Err(DecodeError { description: "invalid wire type value: 6", stack: [] })**
[lenet.zip](https://github.com/tokio-rs/prost/files/7800970/lenet.zip)

**Comment by corleonechensiyu** [comment]
someone can help me . please

**Comment by wmedrano** [comment]
For future reference, please include more details on the underlying file (lenet.prototxt in this case).

Assuming [this is lenet.prototxt](https://github.com/BVLC/caffe/blob/master/examples/mnist/lenet.prototxt), `decode` is meant to parse binary proto format but this is a text proto format.

Note: I'm not sure if prost supports textproto, currently looking into it.

**Comment by wmedrano** [comment]
Related issue #541
