### ISSUE TITLE
Request for new crates.io release w/ LICENSE files

### ISSUE THREAD

**Issue by tjdetwiler** [tokio-rs/prost#622]
Hello!

I'm working on the Fuchsia project and we would like to use prost within or project. We have a license policy that requires explicit license files to be included with any library release from crates.io.

I already have gotten the [PR merged](https://github.com/tokio-rs/prost/pull/619) to place the appropriate LICENSE files into the correct place such that I the next crates.io release should pick them up. Since prost releases relatively infrequently, I wanted to reach out about the possibility of a new patch release (ex: v0.10.1) that contains this explicit LICENSING information.

Thanks!

**Comment by LucioFranco** [comment]
Yeah, I can get a patch out today. Thanks for the heads up.

**Comment by LucioFranco** [comment]
It has been published

**Comment by tjdetwiler** [comment]
Thank you for the quick response!
