### ISSUE TITLE
maintain CHANGELOG

### ISSUE THREAD

**Issue by dvtomas** [tokio-rs/prost#638]
CHANGELOG would be very useful when considering update to a newer version. Right now I have no idea what has changed, if I should update, what are the necessary steps.

**Comment by LucioFranco** [comment]
We kinda keep a changelog via https://github.com/tokio-rs/prost/releases but its not 100% exhaustive but should include what has changed and if you should update etc. We could probably keep a better changelog going forward though.

**Comment by dvtomas** [comment]
Aha, this is probably enough for me, thank you. Perhaps just having CHANGELOG.md with a reference this page would be helpful.

**Comment by LucioFranco** [comment]
Cool, thanks. Gonna close this then.
