### ISSUE TITLE
[prost-build] avoid cmake dependency

### ISSUE THREAD

**Issue by nstinus** [tokio-rs/prost#646]
Today, prost-build tries to find protoc and if it fails, builds it from the vendored sources.
That adds the cmake dependency even though it may not be needed.

Could the default behavior be changed to:
- look for protoc in PROTOC or PATH, then fail.
- if vendored feature is enable, use this one only.

There is the PROTOC_NO_VENDOR env var but the cmake dep is still required.
On top of removing a dependency in some cases, it would also make clearer what is happening.

**Comment by LucioFranco** [comment]
#657 fixes this
