### ISSUE TITLE
prost build seems to nondeterministically fail in C++ protobuf code

### ISSUE THREAD

**Issue by staktrace** [tokio-rs/prost#649]
We have a crate that pulls in prost as a dependency, [here](https://github.com/mozsearch/mozsearch/blob/6f9589a0e351bae1123dd15a333be869e70fe3bf/tools/Cargo.toml#L46). However when building our crate, it seems to sometimes fail during the prost build. I'm attaching a log - the error seems to be in the C++ protobuf code. It's not clear to me why this only happens sometimes or what the root cause is. Filing this issue to track and to see if anybody else has run into this before.

Note that the builds we are doing are on clean EC2 instances based off the same AMI, so the environment in which we're doing the builds should be pretty much the same every time.

[build-log.txt](https://github.com/tokio-rs/prost/files/8691627/build-log.txt)

**Comment by abonander** [comment]
I just encountered something like this while building with a custom Cargo profile: 

```toml
[profile.profiling]
inherits = "release"
debug = true
```

Running `cargo clean` seems to have fixed it.

**Comment by staktrace** [comment]
For now we're going to avoid this problem by having `protoc` installed into the machine image, and so the `prost` build shouldn't try to build protobuf at all.

Feel free to close this issue if it's not affecting anybody else.

**Comment by LucioFranco** [comment]
Yeah, it seems to fail randomly but this is purely trying to build protoc. The real solution is to provide your own protoc if the compiling doesn't work.
