### ISSUE TITLE
enum field not showing up in response when 0

### ISSUE THREAD

**Issue by onx2** [tokio-rs/prost#677]
I have an enum field in proto that I'd like to have returned when I make a request in Postman. I verified the enum will show in the response JSON when it is not a `0`.

```proto
message User {
  string id = 1;
  enum Status {
    ENABLED = 0;
    DISABLED = 1;
    DELETED = 2;
  }

  Status status = 2;
}
``` 

and in postgres the column definition is
```sql
status INT NOT NULL DEFAULT 0,
```

When I return a `Response::new(User { id, status })`, the field `status` is missing when set to `0`. This is the case for the default value applied from postgres as well as an update to the row to set it to `0`. I also verified the data returned from the db, before inserted into the `User` struct includes the `status: 0`.

**Status was saved as  `0`**
```json
{
  "id": "518c36d2-9abd-4d0f-b15b-4b4fb21d2181",
}
```
**Status was saved as  `1`**
```json
{
  "id": "518c36d2-9abd-4d0f-b15b-4b4fb21d2181",
  "status": "DISABLED"
}
```

Moving this question to this repo from https://github.com/hyperium/tonic/issues/1028

**Comment by onx2** [comment]
An update:

I tried this again and am seeing some inconsistent behavior. I set the status of a user to `DELETED`, or rather in the database `3`, and it is not showing up in the response JSON.

**postgres record**
```bash
-[ RECORD 3 ]--------------------------------------
id         | dd2df787-9352-45de-8795-614bb5781ecc
auth_id    | eu est
email      | 
status     | 3
metadata   | 
created_at | 2022-07-04 02:53:14.151034+00
updated_at | 2022-07-04 03:01:46.443734+00
```

**Postman response**
```json
{
    "id": "dd2df787-9352-45de-8795-614bb5781ecc",
    "auth_id": "eu est",
    "created_at": "2022-07-04T02:53:14.151034+00:00",
    "updated_at": "2022-07-04T03:01:46.443734+00:00"
}
```

**Comment by onx2** [comment]
Actually I think this reply answers this question https://github.com/tokio-rs/prost/issues/554#issuecomment-958073921

For clarification, would it be possible and/or bad practice to serialize default values?

**Comment by LucioFranco** [comment]
Might be a better question to ask the protobuf folks. I am not sure but it seems like a good thing to go to the default if there is nothing and also to not serialize if its a default value.
