### ISSUE TITLE
println leftover in code

### ISSUE THREAD

**Issue by horacimacias** [tokio-rs/prost#745]
After updating to the latest 0.11.2 I see some output on stdout being printed.
Looks like this is some leftover println in the code:

https://github.com/tokio-rs/prost/commit/8b412c8edcfa5de1cf5490fceb15e9bab29986c3#diff-cd5e88f54dff8bff01eb95ebd9f12754e0f70fa11adfed2d8323b64f57d1894aR113

is there any reason for this? can this be removed or, if needed, at least have a way to disable this?

**Comment by horacimacias** [comment]
https://github.com/tokio-rs/prost/pull/746

**Comment by LucioFranco** [comment]
Thanks!
