### ISSUE TITLE
#726 breaks build

### ISSUE THREAD

**Issue by matze** [tokio-rs/prost#747]
We have a `build.rs` to add some additional methods to services. Upgrading from 0.11.1 to 0.11.2 caused this (actual binary names and paths redacted)

```
error: failed to run custom build command for `…`

Caused by:
  process didn't exit successfully: `/…/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /…/prost/prost-build/src/lib.rs:1069:52
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I could pinpoint the regressing behaviour to the change commited with #726 however I do not see yet how this causes the `unwrap` to fail. The crash traces from

```rust
    prost_build::Config::new()
        .file_descriptor_set_path(desc_path.clone())
        .skip_protoc_run()
        .extern_path(".foo", "foo_proto")
        .include_file("prost_includes.rs")
        .service_generator(Box::new(gen))
        .compile_protos(&Vec::<&str>::default(), &Vec::<&str>::default())?;
```

in `build.rs` to

```rust
        if let Some(ref mut service_generator) = self.service_generator {
            for (module, package) in packages {
                let buf = modules.get_mut(&module).unwrap();
                service_generator.finalize_package(&package, buf);
            }
        }
```

in the `prost-build/src/lib.rs`.

**Comment by LucioFranco** [comment]
Would it be possible to provide a reproduction proto file I can play around with?

**Comment by matze** [comment]
I will try to come up with a repro build.rs and proto file(s).

**Comment by LucioFranco** [comment]
I just need the proto file really, I can create a test to reproduce and look at it. We may need to yank 0.11.2 then and either fix or remove this commit. Thanks!

**Comment by LucioFranco** [comment]
All good! This has been a really tricky feature that I already had to revert once so getting that edge case test case would be super valuable!

**Comment by matze** [comment]
I could pin it down. As written in the PR, it happens for protos that specify a parent `package`.

**Comment by matze** [comment]
@LucioFranco could you reproduce this issue?

**Comment by matze** [comment]
The issue is actually a combination of the mentioned path hierarchy as well as the fact that we skip generating one particular service causing the output to be empty and hence the module to be removed. So, I will close this issue as a very peculiar case.
