### ISSUE TITLE
prost-build generates rust code for "includes" protos

### ISSUE THREAD

**Issue by horacimacias** [tokio-rs/prost#750]
When using included protos, rust code seems to be generated for all of them regardless of the types actually being needed.

For example, given the following api/helloworld.proto:

```proto
syntax = "proto3";
import "included.proto";
package helloworld;

service HelloWorld {
    rpc SayHello (Hello) returns (Hello) {
    }
}

message Hello {
	string message = 1;
}
```

and the following includes/included.proto:

```proto
syntax = "proto3";

package included;

message Included {
  string name = 1;
}
```

when I run something like:

```rust
  .compile_protos(
            &["./api/helloworld/helloworld.proto"],
            &["./api", "./includes"],
        );
```

prost-build generates a `helloworld.rs` (which is good) **but also an `included.rs file`** (which I believe is bad).

Nowhere in the helloworld.rs is any part of included.rs needed. I can just delete included.rs and the code compiles just fine.

Is there any way to avoid includes having code generated for them?

I understand if the included proto is used, for example a message definition contains a message defined in the include, there is no other way than to generate the rs for the include as well, but what if that is not the case?

This problem gets worse when I use options (e.g. `option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_swagger) = {`) or `  option (google.api.http) = {
            get: "/api/v1/hello-world/greet"
        };` where a pile of non-required .rs files get generated and I'm trying to avoid that.

**Comment by LucioFranco** [comment]
If they are not used why is it included?

**Comment by LucioFranco** [comment]
Prost isn't smart enough to figure out if you use it or not.

**Comment by horacimacias** [comment]
Thanks. Do we want to make it smart enough to understand that?
Or to make it ignore proto options, given we know we're not generating any code based on them?

**Comment by LucioFranco** [comment]
I would say you can write custom logic in your build.rs to delete the packages you don't want. That seems like a better solution to me than adding this into prost.
