### ISSUE TITLE
`println!` in `prost-build` causing issues for `protoc-gen-prost`

### ISSUE THREAD

**Issue by neoeinstein** [tokio-rs/prost#756]
[Introduced in v0.11.2](https://sourcegraph.com/crates/prost-build/-/compare/v0.11.1...v0.11.2#diff-bbff921c19d129ecd0dda049b127e8d1R113). `protoc` uses `stdout` for communications with plugins, so anything unexpectedly printing to standard out poses problems for us.

Will create a PR shortly.

Originally reported as part of neoeinstein/protoc-gen-prost#33

**Comment by neoeinstein** [comment]
Looks like this was taken care of in #746. Just would need a release to allow some users to avoid binding to 0.11.2. (I've recommended that consumers use `--locked` to avoid accidentally getting the latest version of `prost-build`).

**Comment by LucioFranco** [comment]
Yeah, I can get a new release out this week. Totally missed it in my review step :D
