### ISSUE TITLE
Stable content of include file

### ISSUE THREAD

**Issue by rekby** [tokio-rs/prost#757]
I use tonic_build with .include_file("mod.rs") option.
It set include_file option in prost_build config.

Now on every start it generate modules in mod.rs in random order. It cause problems:
1. It make difficult to check regenerated code in CI (it always diff from committed).
2. It is difficult to see real changes in the include file.

I suggest sort modules before write them to the include file.

**Comment by LucioFranco** [comment]
I believe it should generate them in the same order but if you have a reproduction that shows it generates them in diff orders I can take a look.

**Comment by rekby** [comment]
I used old version of prost (0.11.0), you are fixed the problem in 0.11.2 already. Thanks :)

It is not reproduced after I update prost to 0.11.2
