### ISSUE TITLE
Generate .proto from existing structs

### ISSUE THREAD

**Issue by caamartin35** [tokio-rs/prost#772]
I was wondering if it is possible to generate proto messages from existing rust structs.

I have the following struct:
```rust
#[derive(Copy, Clone, Serialize, Message)]
pub struct Node {
  pub node_id: i32,
  pub left_id: Option<i32>,
  pub right_id: Option<i32>,
  pub strength: f32,
  pub level: i32,
  pub right_parents: i32,
  pub left_parents: i32,
}
```

This struct is a core component of my application, and I want it to be the source of truth. Ideally, I would like to generate a proto based on it. 

At the end of the README it states to do something like this:

```rust
#[derive(Copy, Clone, Serialize, Message)]
pub struct Node {
  #[prost(int32)]
  pub node_id: i32,
  #[prost(int32, optional)]
  pub left_id: Option<i32>,
  #[prost(int32, optional)]
  pub right_id: Option<i32>,
  #[prost(float)]
  pub strength: f32,
  #[prost(int32)]
  pub level: i32,
  #[prost(int32)]
  pub right_parents: i32,
  #[prost(int32)]
  pub left_parents: i32,
}
```

But even when I do this I am still required to create a .proto file with:
```
message Node {
  int32 node_id = 1;
  optional int32 left_id = 3;
  optional int32 right_id = 4;
  float strength = 5;
  int32 level = 6;
  int32 right_parents = 7;
  int32 left_parents = 8;
}
```

I really just want a way to use my struct as the source of truth and generate a proto from it without having to repeat the structure in a .proto file manually. The Node struct could change, and I don't want every developer to be responsible for making sure the structure changes in both the core of the application and the proto. Is this possible or is it not how Prost is meant to be used. 

Thanks a lot!

**Comment by LucioFranco** [comment]
This has been asked for a few times but its out of scope for prost. It would be better to build this externally for your own use case.
