### ISSUE TITLE
[prost-build] Add Message and Enum specific attributes

### ISSUE THREAD

**Issue by damelLP** [tokio-rs/prost#783]
I have a large-ish api and want to be able to auto-generate `derive_builder` builders for it similar to here #399.

From the code-generator it seems to be an easy addition of just adding the builder functions.
Example usage looks like this.
```rust
        prost_build::Config::new()
        .message_attribute(".", "#[derive(derive_builder::Builder)]")
        .compile_protos(...)
```

**Comment by LucioFranco** [comment]
Could you explain why you need a message attribute over https://docs.rs/prost-build/latest/prost_build/struct.Config.html#method.type_attribute using this?

**Comment by damelLP** [comment]
Hi @LucioFranco, yes, the type attribute is applied to all the different types that get generated, and the derive builder attribute fails to compile on enums.
```sh
error: Unsupported shape `enum`
   --> src/gen/api.rs:401:10
    |
401 | #[derive(derive_builder::Builder)]
    |          ^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by LucioFranco** [comment]
Got it I think that makes sense.
