### ISSUE TITLE
Feature request: Optionally leave out Debug impl

### ISSUE THREAD

**Issue by audunska** [tokio-rs/prost#795]
We are using tonic, prost and tracing in a service handling customer data. All of our endpoint handler functions look like for example
```rust
#[instrument(skip(self))]
async fn handle_search_files(
    &self,
    request: SearchFilesRequest,
) -> Result<Response<SearchFilesStream>, Status> {
    ...
}
```
where the `SearchFilesRequest` is a prost message. This pushes the request body to the tracing provider using its `Debug` implementation. However, we would like to limit the amount of customer data pushed to the tracing provider, while still seeing the structure of the request as well as internal ids.

Possible ways of doing this is to manually go through all the endpoints and only push allowed fields to tracing, or to wrap all the request objects in a custom wrapper type with a restricted Debug impl. However, this seems quite brittle and boilerplate-heavy.

One solution that would be really neat is to derive our own Debug impl for the messages, by using a prost_build config with `.type_attribute(".", "#[derive(CustomDebug)]")`. This custom debug deriver could then consult an internal allowlist for which fields to include in the debug output, and which fields to leave out. However, this is not possible if `prost_build` already provides its own `Debug`.

So, my question is: Would it be possible to optionally leave out the Debug impl for messages and oneofs?

**Comment by LucioFranco** [comment]
Yeah, I think we can just do this https://docs.rs/prost-build/latest/prost_build/struct.Config.html#method.disable_comments but for debug impl? Should be pretty easy to add and isn't a breaking change.

**Comment by audunska** [comment]
> Yeah, I think we can just do this https://docs.rs/prost-build/latest/prost_build/struct.Config.html#method.disable_comments but for debug impl? Should be pretty easy to add and isn't a breaking change.

You would think that, but the Debug impl is generated in `prost-derive` as part of the `#[derive(Message)]` and friends, and that doesn't have access to the config. I guess we could add a struct attribute to control whether `Debug` is generated.

**Comment by LucioFranco** [comment]
Ah you're right, maybe we can have a attribute option that sets no debug and then that can be enabled via prost-build.

**Comment by audunska** [comment]
> Ah you're right, maybe we can have a attribute option that sets no debug and then that can be enabled via prost-build.

Yes, I am investigating this option.

**Comment by AlJohri** [comment]
Related: #334 and #367

**Comment by caspermeijn** [comment]
- If your code is generated by `prost_build`, then you can configure that to not generate a `impl Debug` with https://docs.rs/prost-build/latest/prost_build/struct.Config.html#method.skip_debug
- If your code uses `prost_derive`, then the `skip_debug` attribute exists: https://docs.rs/prost-derive/0.13.3/src/prost_derive/lib.rs.html#25
- Currently an `impl Debug` is required for each `prost::Message`, but that requirement is relaxed in this PR: https://github.com/tokio-rs/prost/pull/1147

If this comment helps you, please consider updating the crate documentation to make these features more findable.
