### ISSUE TITLE
Output gets written to top level OUT_DIR by default

### ISSUE THREAD

**Issue by JanBeh** [tokio-rs/prost#808]
I think it is a bad idea to write the generated Rust code to the top level `OUT_DIR` by default as this may cause collisions with other output during the build process. How about writing the output to "protobuf/" or "protos/" (or something similar) by default? I'm not sure though. See also #426 (and my [comment](https://github.com/tokio-rs/prost/issues/426#issuecomment-1415739563)), where an unnamed package gets written to `_.rs` in the topmost directory (which certainly isn't good).

**Comment by LucioFranco** [comment]
I don't totally follow the real problem of going directly to out_dir but you can configure it to any `out_dir` via the build config struct. So if you do hit this there is an easy work around.

**Comment by JanBeh** [comment]
When writing files, it's generally a good idea to avoid potential collisions. Using the proto package name in the toplevel directory seems to be a bad idea. That's why I opened this issue.

**Comment by LucioFranco** [comment]
> When writing files, it's generally a good idea to avoid potential collisions. Using the proto package name in the toplevel directory seems to be a bad idea. That's why I opened this issue.

First thank you for opening an issue! I think in this case, we are fine since 1) this is a compile issue so something that will be caught quite early on 2) there is a pretty easy fix for users.
