### ISSUE TITLE
Efficient encoding to utf-8

### ISSUE THREAD

**Issue by 0xAlcibiades** [tokio-rs/prost#911]
I'm wanting to encode protobuf messages from tonic to be passed via Redis. Wondering if anyone out there has hit this need, and if there exists a good encoding to UTF-8 excluding something like base64.

**Comment by caspermeijn** [comment]
- You can encode the message to a bytebuffer, but that doesn't guarantee a valid UTF-8 string. You would need something like base64 for the conversion from the bytebuffer to UTF-8. https://docs.rs/prost/latest/prost/trait.Message.html
- protobuf does define a JSON mapping for its messages. However, `prost` will not help you with the conversion to/from JSON. https://protobuf.dev/programming-guides/proto3/#json
