### ISSUE TITLE
Error when cross compiling using `cross build`

### ISSUE THREAD

**Issue by Danvil** [tokio-rs/prost#929]
When cross-compiling a program using prost with `cross` I get the following error:
```
 Error: Custom { kind: Other, error: "protoc failed: " }
```

Host: Windows
Target: aarch64-unknown-linux-gnu
Cross configured to use podman

**Comment by crazystylus** [comment]
Hi @Danvil ,
Can you share your `Cross.toml`?

I am able to using Cross and Prost and cross compile to various architectures. Here's a link to [`Cross.toml`](https://github.com/crazystylus/otadump/blob/mainline/Cross.toml) from one of my repo.

**Comment by crazystylus** [comment]
It looks like an old version of protobuff-compiler is being installed. Can
you also try adding image name similar to the cross.toml from pervious
comment? Adding the image name will ensure that you are using latest
version of container image.
