### ISSUE TITLE
Can you clarify whether prost works with no_std?

### ISSUE THREAD

**Issue by shutej** [tokio-rs/prost#942]
I attempted to add the dependencies documented in README.md this morning:

https://github.com/tokio-rs/prost#using-prost-in-a-no_std-crate

...but got the following:

```shell
cargo build
   Compiling bytes v0.5.6
error[E0463]: can't find crate for `std`
  --> /Users/shutej/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bytes-0.5.6/src/lib.rs:82:1
   |
82 | extern crate std;
   | ^^^^^^^^^^^^^^^^^ can't find crate
   |
   = note: the `thumbv7em-none-eabihf` target may not support the standard library

For more information about this error, try `rustc --explain E0463`.
error: could not compile `bytes` (lib) due to previous error
```

**Comment by shutej** [comment]
This is a problem with the version mentioned in the docs.  Use `cargo add prost` instead, folks.

**Comment by caspermeijn** [comment]
As I understand, you used an older version. The new version does support `no_std` as you expect.

The readme has the most recent version number. I have fixed the release script to update the readme during the release process. You are welcome to reopen a PR to use `cargo add`.
