### ISSUE TITLE
prost-build doc link broken on docs.rs

### ISSUE THREAD

**Issue by paxsonsa** [tokio-rs/prost#960]
On the main page for Prost, the link to prost-build is linking to the readme path in the repo. This works on Crates and GitHub but breaks on doc.rs

Happy to submit a fix but wondering if we prefer for it to link to doc.rs or continue to link to GitHub?

**Comment by paxsonsa** [comment]
This link:
https://github.com/tokio-rs/prost/blob/master/README.md?plain=1#L39

**Comment by caspermeijn** [comment]
Fixed in https://github.com/tokio-rs/prost/pull/967
