### ISSUE TITLE
`prost-types` crate missing Well Known Types from google.protobuf.wrapper

### ISSUE THREAD

**Issue by adrianojsoares1** [tokio-rs/prost#964]
I would like to know if this was an intentional design decision, or if `google.protobuf.wrapper` Well Known Types should be added to `prost-types`.

### Summary

The README of `prost-types` suggests reviewing the [official protocol buffers WKT documentation](https://protobuf.dev/reference/protobuf/google.protobuf/). However, there are several types listed in this documentation that are absent from `prost-types`. These include: `BoolValue`, `BytesValue`, `DoubleValue`, `FloatValue`, `Int64Value`, `Int32Value`, `UInt32Value`, `UInt64Value`, and `StringValue`. All of these can be traced back a single protofile definition - Google's [wrappers.proto](https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/wrappers.proto).

The definitions of these messages are not complicated, for example, `Int64Value`:
```proto
message Int64Value {
  int64 value = 1;
}
```

But they are available in Protocol Buffers packages of other languages. For example, in Python you could do:

```python
from google.protobuf import wrappers_pb2
integer_message = wrappers_pb2.Int64Value(value=1)
```

I wonder, is there a particular reason these simple wrapper classes are missing, and should they be added to `prost-types` in a future release?

### Suggestion
Generate Rust structs from the `wrappers.proto` definition to match the Protocol Buffers Well Known Types documentation.

**Comment by mumbleskates** [comment]
checkout `src/types.rs` in the main `prost` crate and you'll like what you find.
