### ISSUE TITLE
How to customize grpc method uri

### ISSUE THREAD

**Issue by caibirdme** [tokio-rs/prost#973]
```proto
service Foo {
  rpc hello(xx) return xx;
}
```

How can I set the generated grpc uri for hello method is `whatever.i.want.to.set.FooService/hi`

**Comment by caspermeijn** [comment]
I am not sure what you are asking. 

- It sounds like you are not very familiar with protobuf definitions. In that case, you want to read the protobuf documentation and specifically look at the `package` keyword: https://protobuf.dev/programming-guides/proto3/#packages
- Maybe you are looking for an advanced feature for setting a domain name for a type using https://docs.rs/prost-build/latest/prost_build/struct.Config.html#method.type_name_domain
